version: 1

formatters:
  defaultFormatter:
    format: '%(asctime)s | %(levelname)-8s | %(name)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  devFormatter:
    format: '%(asctime)s | %(levelname)-8s | %(name)s | %(filename)s:%(lineno)d:%(funcName)s() | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: defaultFormatter
    stream: ext://sys.stdout

  devConsoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: devFormatter
    stream: ext://sys.stdout

loggers:
  dropspy:
    level: INFO
    handlers: [consoleHandler]
    propagate: True

  dropspy.test:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: True

  dropspy.pipeline:
    level: INFO
    handlers: [consoleHandler]
    propagate: False

  dropspy.telegram:
    level: INFO
    handlers: [consoleHandler]
    propagate: True

  dropspy.pipeline.batch:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False

  dropspy.telegram.api_adapter:
    level: DEBUG
    handlers: [devConsoleHandler]
    propagate: True

disable_existing_loggers: False
