version: 1

formatters:
  defaultFormatter:
    format: '%(asctime)s | %(levelname)-8s | %(name)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  devFormatter:
    format: '%(asctime)s | %(levelname)-8s | %(name)s | %(filename)s:%(lineno)d:%(funcName)s() | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: defaultFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.FileHandler
    level: INFO
    formatter: defaultFormatter
    filename: placeholder.log
    encoding: utf-8

  devConsoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: devFormatter
    stream: ext://sys.stdout

loggers:
  dropspy:
    level: INFO
    propagate: True

  dropspy.tests:
    level: DEBUG
    propagate: True

  dropspy.tests.e2e:
    level: DEBUG
    propagate: True

  dropspy.pipeline:
    level: DEBUG
    propagate: True

  dropspy.telegram:
    level: DEBUG
    propagate: True

  dropspy.pipeline.batch:
    level: DEBUG
    propagate: True

  dropspy.pipeline.fetch:
    level: DEBUG
    propagate: True

  dropspy.telegram.api_adapter:
    level: DEBUG
    propagate: True

disable_existing_loggers: False
